data = dlmread("harmonic0.001", "'\t'");
t = data(:,1);
beemanPos = data(:,2);
gpco5Pos = data(:, 3);
verlet = data(:,4);
analyticPos = data(:, 5);
plot(t, beemanPos, ";Beeman;", t, verlet, ";Verlet Leap Frog;", t, gpco5Pos, ";GPCO5;", t, analyticPos, ";Analytic;");
#plot(t, verlet, ";Verlet;", t, analyticPos, ";Analytic;");
#plot(t, beemanPos, ";Beeman;", t, analyticPos, ";Analytic;");
#plot(t, gpco5Pos, ";GPCO5;", t, analyticPos, ";Analytic;");
title ("Aproximation Dt = 0.001");
xlabel ("Tiempo (s)");
ylabel ("Posicion(m)");